theme: jekyll-theme-slate
title: Hacktitude-2023
description: Are you the best in the league? Participate in Hacktitude, earn 99 points, and prove what you are worth!
github:
  is_project_page: false
